siyyana_app/urls.py
from django.urls import path,include
from siyyana_app import views

app_name = 'siyyana_app'
urlpatterns = [
    
    
    path('', views.login,name='login'),
    path('admin-logout', views.admin_logout,name='admin_logout'),
    
    path('dashboard', views.index,name='index'),
    path('services', views.services,name='services'),
    path('add-services', views.add_services,name='add_services'),
    path('edit-services/<int:id>/', views.edit_services,name='edit_services'),
    path('delete-services/<int:id>/', views.delete_services,name='delete_services'),


    path('sub-services', views.sub_services,name='sub_services'),
    path('add-subservices', views.add_subservices,name='add_subservices'),
    path('edit-subservices/<int:id>/', views.edit_subservices,name='edit_subservices'),
    path('delete-subservices/<int:id>/', views.delete_subservices,name='delete_subservices'),

    path('top-services', views.top_services,name='top_services'),
    path('add-topservices', views.add_topservices,name='add_topservices'),
    path('edit-topservices/<int:id>/', views.edit_topservices,name='edit_topservices'),
    path('delete-topservices/<int:id>/', views.delete_topservices,name='delete_topservices'),

    path('top-subservices', views.top_subservices,name='top_subservices'),
    path('add-top-subservices', views.add_top_subservices,name='add_top_subservices'),
    path('delete-topsubservices/<int:id>/', views.delete_topsubservices,name='delete_topsubservices'),

    

    

    path('employee-list', views.employee_list,name='employee_list'),
    path('employee-delete/<int:id>/', views.employee_delete,name='employee_delete'),
    
    path('requested-services', views.requested_services,name='requested_services'),
    path('change-requested-services-status/<int:pk>/<str:new_status>/', views.change_requested_services_status, name='change_requested_services_status'),
    path('delete-requested-services/<int:id>/', views.delete_requested_services,name='delete_requested_services'),
    

    path('user-list', views.user_list,name='user_list'),
    path('user-delete/<int:id>/', views.user_delete,name='user_delete'),

    path('country', views.country,name='country'),
    path('add-country', views.add_country,name='add_country'),
    path('edit-country/<int:id>/', views.edit_country,name='edit_country'),
    path('country-delete/<int:id>/', views.country_delete,name='country_delete'),
    # path('import-excel-country', views.import_excel_country,name='import_excel_country'),

    

    path('state', views.state,name='state'),
    path('add-state', views.add_state,name='add_state'),
    path('edit-state/<int:id>/', views.edit_state,name='edit_state'),
    path('state-delete/<int:id>/', views.state_delete,name='state_delete'),

    path('district', views.district,name='district'),
    path('add-district', views.add_district,name='add_district'),
    path('edit-district/<int:id>/', views.edit_district,name='edit_district'),
    path('district-delete/<int:id>/', views.district_delete,name='district_delete'),

    path('view-profile/<int:id>/', views.view_profile,name='view_profile'),
    path('staff-status-change/<int:id>/', views.staff_status_change, name='staff_status_change'),
    
    path('onboarding', views.onboarding,name='onboarding'),
    path('add-onboarding', views.add_onboarding,name='add_onboarding'),
    path('edit-onboarding/<int:id>/', views.edit_onboarding,name='edit_onboarding'),
    path('onboarding-delete/<int:id>/', views.onboarding_delete,name='onboarding_delete'),

    path('currency-type', views.currency_type,name='currency_type'),
    path('add-currency-type', views.add_currency_type,name='add_currency_type'),
    path('currency-delete/<int:id>/', views.currency_delete,name='currency_delete'),

    

]

siyyana_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('siyyana_app.urls')),
    path('user-api/', include('user_api.urls')),
    path('employee-api/', include('employee_api.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

user_api/urls.py
from django.urls import path,include
from user_api.views import *

urlpatterns = [
    
    path('user-registration', UserRegistration.as_view(), name='user-registration'),
    path('user-login', UserLogin.as_view(), name='user-login'),

    path('request-otp/', request_otp, name='request_otp'),
    path('verify-otp/', verify_otp, name='verify_otp'),
    path('reset-password/', reset_password, name='reset_password'),

    
    path('category-with-subcategory-and-employees', category_with_subcategory_and_employees, name='category-with-subcategory-and-employees'),
    path('all-categories', all_categories, name='all-categories'), 
    
    path('user-profile-api', user_profile_api, name='user-profile-api'),
    path('edit-user-profile', edit_user_profile, name='edit-user-profile'),
    path('search-by-category', search_by_category, name='search-by-category'), 
    path('save-employee', save_employee, name='save-employee'),
    path('booking-api', booking_api, name='booking-api'),
    path('reschedule-booking', reschedule_booking, name='reschedule-booking'),

    path('my-orders-user-api', my_orders_user_api, name='my-orders-user-api'),
    path('post-review', post_review, name='post-review'),
    path('popular-categories', popular_categories, name='popular_categories'),

    path('category-subcategory-list', category_subcategory_list, name='category_subcategory_list'),





]

templates/add-currency-type.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}

{% block pageheading %}
Add Currency Type
{% endblock %}


<!-- Page Sidebar Ends-->
<div class="page-body">
  <!-- Container-fluid starts-->
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <div class="card" style='width: 1019px; margin-left: 96px;'>
          <div class="card-body">
            <form method='post' enctype='multipart/form-data'>
              {% csrf_token %}
            <div class="form theme-form">
              <div class="row">
                <div class="col-lg-6">
                  <div class="mb-3">
                    <label>Currency name</label>
                    {{form.name}}
                  </div>
                  
                </div>
              
              </div>
              

            
              </div>
              <div class="row">
                <div class="col">
                  <div class="text-end">
                    <input type='submit' class="btn me-3 custom-submit-btn" value='Submit'>
                    <a class="btn btn-danger" href="#" onclick="window.history.back(); return false;">Cancel</a>
                  </div>
                </div>
              </div>
            </div>
          </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Container-fluid Ends-->
</div>


<script>
  document.getElementById('convert').addEventListener('click', function() {
    const packageName = document.getElementById('id_category_name').value;
    convertToArabic(packageName);
  });

  function convertToArabic(text) {
    const url = `https://api.mymemory.translated.net/get?q=${encodeURIComponent(text)}&langpair=en|ar`;

    fetch(url)
      .then(response => response.json())
      .then(data => {
        const translatedText = data.responseData.translatedText;
        document.getElementById('id_category_name_arabia').value = translatedText;
      })
      .catch(error => {
        console.error('Error:', error);
      });
  }
</script>


{% endblock %}

templates/country.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}

{% block pageheading %}
Country
{% endblock %}


      <!-- Page Sidebar Ends-->
      <div class="page-body">
        <!-- Container-fluid starts-->
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-12">
              <div class="card">
                <div class="card-body">
                  {% comment %} <form method="post" action="{% url 'siyyana_app:import_excel_country' %}" class="row g-3 mb-2">
                    {% csrf_token %}
                    <div class="col-md-2">
                      <input type="file" class="form-control form-control-sm" name="excel_file" required>
                    </div>
                    <div class="col-md-1">
                        <input type="submit" class="btn btn-primary" value="Import excel">
                    </div>
                </form> {% endcomment %}
                  <div class="list-product-header">
                    
                    <div>
                      <a class="btn"  style="background-color: #086b94; border-color: #086b94; color: white;" href="{% url 'siyyana_app:add_country' %}"
                        ><i class="fa fa-plus"></i>Add Country</a
                      >
                    </div>
                    
                  <div class="list-product">
                      <table class="display" id="row-select-delete">
                        <thead>
                          <tr>
                            <th>SL</th>
                            <th>Country Name</th>
                            <th>Flag</th>
                            <th>Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          {% for i in data %}
                          <tr>
                            <td>{{forloop.counter }}</td>
                            <td>{{i.name}}</td>
                            {% if i.flag %}
                            <td><img src='{{i.flag.url}}' style="width:30px;height:30px;"></td>
                            {% else %}
                            <td>None</td>
                            {% endif %}
                            <td>
                              <ul class="action">
                                <li class="edit">
                                  <a href="{% url 'siyyana_app:edit_country' i.id %}"
                                    ><i class="icon-pencil-alt"></i
                                  ></a>
                                </li>
                                <li class="delete">
                                  <a  onclick="showConfirmation('{%  url 'siyyana_app:country_delete' i.id %}')"><i class="icon-trash me-2"></i></a>
                                </li>
                              </ul>
                            </td>
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Container-fluid Ends-->
      </div>
      <!-- footer start-->


{% endblock content %}

templates/district.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}

{% block pageheading %}
District
{% endblock %}


      <!-- Page Sidebar Ends-->
      <div class="page-body">
        <!-- Container-fluid starts-->
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-12">
              <div class="card">
                <div class="card-body">
                  <div class="list-product-header">
                    <div>
                      <a class="btn"  style="background-color: #086b94; border-color: #086b94; color: white;" href="{% url 'siyyana_app:add_district' %}"
                        ><i class="fa fa-plus"></i>Add District</a
                      >
                    </div>
                    
                  <div class="list-product">
                      <table class="display" id="row-select-delete">
                        <thead>
                          <tr>
                            <th>SL</th>
                            <th>District</th>
                            <th>State</th>
                            <th>Country</th>
                            <th>Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          {% for i in data %}
                          <tr>
                            <td>{{forloop.counter }}</td>
                            <td>{{i.name}}</td>
                            <td>{{i.state}}</td>
                            <td>{{i.state.country}}</td>
                            <td>
                              <ul class="action">
                                <li class="edit">
                                  <a href="{% url 'siyyana_app:edit_district' i.id %}"
                                    ><i class="icon-pencil-alt"></i
                                  ></a>
                                </li>
                                <li class="delete">
                                  <a  onclick="showConfirmation('{%  url 'siyyana_app:district_delete' i.id %}')"><i class="icon-trash me-2"></i></a>
                                </li>
                              </ul>
                            </td>
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Container-fluid Ends-->
      </div>
      <!-- footer start-->


{% endblock content %}

templates/employee.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}

{% block pageheading %}
Employees
{% endblock %}


      <!-- Page Sidebar Ends-->
      <div class="page-body">
        <!-- Container-fluid starts-->
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-12">
              <div class="card">
                <div class="card-body">
                    <form method="get" class="row g-3 mb-2">
                        <div class="col-md-2">
                            <select class="form-select form-select-sm" name="country" style="margin-right: 1rem;">
                                <option value="All">Country</option>
                                {% for country in countries %}
                                    <option value="{{ country.id }}" {% if country.id|stringformat:"s" == request.GET.country %}selected{% endif %}>{{ country.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    
                      
                        <div class="col-md-2">
                            <select class="form-select form-select-sm" name="state" style="margin-right: 1rem;">
                                <option value="All">State</option>
                                {% for state in states %}
                                    <option value="{{ state.id }}" {% if state.id|stringformat:"s" == request.GET.state %}selected{% endif %}>{{ state.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    
                        <div class="col-md-2">
                            <select class="form-select form-select-sm" name="district" style="margin-right: 1rem;">
                                <option value="All">District</option>
                                {% for district in districts %}
                                    <option value="{{ district.id }}" {% if district.id|stringformat:"s" == request.GET.district %}selected{% endif %}>{{ district.name }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="col-md-2">
                            <select class="form-select form-select-sm" name="category" style="margin-right: 1rem;">
                                <option value="All">Category</option>
                                {% for category in categories %}
                                    <option value="{{ category.id }}" {% if category.id|stringformat:"s" == request.GET.category %}selected{% endif %}>{{ category.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        
                    
                        <div class="col-md-2">
                            <select class="form-select form-select-sm" name="subcategory" style="margin-right: 1rem;">
                                <option value="All">Sub Category</option>
                                {% for subcategory in subcategories %}
                                    <option value="{{ subcategory.id }}" {% if subcategory.id|stringformat:"s" == request.GET.subcategory %}selected{% endif %}>{{ subcategory.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    
                        <!-- Buttons Section, aligned to the right -->
    <div class="col-md-2 d-flex justify-content-end align-items-center">
        <input type="submit" class="btn btn-primary me-2" value="Filter">
        <button type="submit" class="btn btn-success" name="export_excel" value="1" title="Export to Excel">
            <i class="fas fa-file-excel"></i>
        </button>
    </div>
                    </form>
                    
                  <div class="list-product-header">
                    {% comment %} <div>
                      <a class="btn"  style="background-color: #086b94; border-color: #086b94; color: white;" href="{% url 'siyyana_app:add_services' %}"
                        ><i class="fa fa-plus"></i>Add Employees</a
                      >
                    </div> {% endcomment %}
                    
                  <div class="list-product"  style="overflow-x: auto;">
                    <table class="display" id="row-select-delete">
                      <thead>
                          <tr>
                              <th>SL</th>
                              <th>Name</th>
                              <th>Email</th>
                              <th>Completed Bookings</th> <!-- New column -->
                              <th>Mobile Number</th>
                              <th>WhatsApp Number</th>
                              <th>Profile Picture</th>
                              <th>Status</th>
                              <th>Action</th>
                              <th>Country</th>
                              <th>State</th>
                              <th>District</th>
                          </tr>
                      </thead>
                      <tbody>
                          {% for user in users %}
                          <tr>
                              <td>{{ forloop.counter }}</td>
                              <td>{{ user.name }}</td>
                              <td>{{ user.email }}</td>
                              <td>{{ user.completed_bookings_count }}</td> <!-- Completed bookings count -->

                              <td>
                                  <a href="tel:{{ user.mobile_number }}">
                                      <i class="fas fa-phone"></i> {{ user.mobile_number }}
                                  </a>
                              </td>
                              <td>
                                  <a href="https://wa.me/{{ user.whatsapp_number }}" target="_blank">
                                      <i class="fab fa-whatsapp"></i> {{ user.whatsapp_number }}
                                  </a>
                              </td>
                              <td>
                                  {% if user.profile_picture %}
                                      <img src="{{ user.profile_picture.url }}" style="width:49px;height:50px;">
                                  {% else %}
                                      None
                                  {% endif %}
                              </td>
                              <td>
                                  {% if user.status == 'Active' %}
                                      <label class="switch">
                                          <input type="checkbox" class="checkbox-category" data-category-url="{% url 'siyyana_app:staff_status_change' user.id %}" checked>
                                          <span class="slider round"></span>
                                      </label>
                                  {% else %}
                                      <label class="switch">
                                          <input type="checkbox" class="checkbox-category" data-category-url="{% url 'siyyana_app:staff_status_change' user.id %}">
                                          <span class="slider round"></span>
                                      </label>
                                  {% endif %}
                              </td>
                              <td>
                                  <ul class="action">
                                      <li class="delete">
                                          <a onclick="showConfirmation('{% url 'siyyana_app:employee_delete' user.id %}')">
                                              <i class="icon-trash me-2"></i>
                                          </a>
                                      </li>
                                      <li class="delete">
                                          <a href="{% url 'siyyana_app:view_profile' user.id %}">
                                              <i class="icon-eye me-2"></i>
                                          </a>
                                      </li>
                                  </ul>
                              </td>
                              <td>{{ user.country }}</td>
                              <td>{% if user.state.all %}{{ user.state.all|join:", " }}{% endif %}</td>
                              <td>{% if user.district.all %}{{ user.district.all|join:", " }}{% endif %}</td>
                          </tr>
                          {% endfor %}
                      </tbody>
                  </table>
                  
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Container-fluid Ends-->
      </div>
      <!-- footer start-->


{% endblock content %}

templates/requested-services.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}

{% block pageheading %}
Requested Services
{% endblock %}


      <!-- Page Sidebar Ends-->
      <div class="page-body">
        <!-- Container-fluid starts-->
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-12">
              <div class="card">
                <div class="card-body">
                  {% comment %} <form method="post" action="{% url 'siyyana_app:import_excel_country' %}" class="row g-3 mb-2">
                    {% csrf_token %}
                    <div class="col-md-2">
                      <input type="file" class="form-control form-control-sm" name="excel_file" required>
                    </div>
                    <div class="col-md-1">
                        <input type="submit" class="btn btn-primary" value="Import excel">
                    </div>
                </form> {% endcomment %}
                  <div class="list-product-header">
                    
                    {% comment %} <div>
                      <a class="btn"  style="background-color: #086b94; border-color: #086b94; color: white;" href="{% url 'siyyana_app:add_country' %}"
                        ><i class="fa fa-plus"></i>Add Country</a
                      >
                    </div>
                     {% endcomment %}
                  <div class="list-product">
                      <table class="display" id="row-select-delete">
                        <thead>
                          <tr>
                            <th>SL</th>
                            <th>Service</th>
                            <th>Sub Services</th>
                            <th>Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          {% for i in requested_services %}
                          <tr>
                            <td>{{forloop.counter }}</td>
                            <td>{{i.name}}</td>
                            <td>{{i.subcategory}}</td>
                            <td>
                              <ul class="action">
                              
                                <li class="delete">
                                  <a  onclick="showConfirmation('{%  url 'siyyana_app:delete_requested_services' i.id %}')"><i class="icon-trash me-2"></i></a>
                                </li>
                              </ul>
                            </td>
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Container-fluid Ends-->
      </div>
      <!-- footer start-->


{% endblock content %}

templates/services.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}

{% block pageheading %}
Services
{% endblock %}


      <!-- Page Sidebar Ends-->
      <div class="page-body">
        <!-- Container-fluid starts-->
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-12">
              <div class="card">
                <div class="card-body">
                  <div class="list-product-header">
                    <div>
                      <a class="btn"  style="background-color: #086b94; border-color: #086b94; color: white;" href="{% url 'siyyana_app:add_services' %}"
                        ><i class="fa fa-plus"></i>Add Services</a
                      >
                    </div>
                    
                  <div class="list-product">
                      <table class="display" id="row-select-delete">
                        <thead>
                          <tr>
                            <th>SL</th>
                            <th>Service name</th>
                            <th>Image</th>
                            <th>Color</th>
                            <th>Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          {% for i in data %}
                          <tr>
                            <td>{{forloop.counter }}</td>
                            <td>{{i.name}}</td>
                            <td><img src="{{i.logo.url}}" style="width:49px;height:50px;"></td>
                            <td><span style="background-color: {{ i.color }}; padding: 5px 10px; color: white;"></td>
                            <td>
                              <ul class="action">
                                <li class="edit">
                                  <a href="{% url 'siyyana_app:edit_services' i.id %}"
                                    ><i class="icon-pencil-alt"></i
                                  ></a>
                                </li>
                                <li class="delete">
                                  <a  onclick="showConfirmation('{%  url 'siyyana_app:delete_services' i.id %}')"><i class="icon-trash me-2"></i></a>
                                </li>
                              </ul>
                            </td>
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Container-fluid Ends-->
      </div>
      <!-- footer start-->


{% endblock content %}

templates/top-services.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}

{% block pageheading %}
Top Services
{% endblock %}


      <!-- Page Sidebar Ends-->
      <div class="page-body">
        <!-- Container-fluid starts-->
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-12">
              <div class="card">
                <div class="card-body">
                  <div class="list-product-header">
                    <div>
                      <a class="btn"  style="background-color: #086b94; border-color: #086b94; color: white;" href="{% url 'siyyana_app:add_topservices' %}"
                        ><i class="fa fa-plus"></i>Add Top Services</a
                      >
                    </div>
                    
                  <div class="list-product">
                      <table class="display" id="row-select-delete">
                        <thead>
                          <tr>
                            <th>SL</th>
                            <th>Category name</th>
                            <th>Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          {% for i in data %}
                          <tr>
                            <td>{{forloop.counter }}</td>
                            <td>{{i.Category.name}}</td>
                            <td>
                              <ul class="action">
                                {% comment %} <li class="edit">
                                  <a href="{% url 'siyyana_app:edit_topservices' i.id %}"
                                    ><i class="icon-pencil-alt"></i
                                  ></a>
                                </li> {% endcomment %}
                                <li class="delete">
                                  <a  onclick="showConfirmation('{%  url 'siyyana_app:delete_topservices' i.id %}')"><i class="icon-trash me-2"></i></a> 
                                </li>
                              </ul>
                            </td>
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Container-fluid Ends-->
      </div>
      <!-- footer start-->


{% endblock content %}